import type { DangerResults } from "../dsl/results.ts"
import type { Violation } from "../dsl/types.ts"
import { isInline } from "../dsl/types.ts"

/**
 * Converts a set of violations into an HTML table.
 */
function table(name: string, defaultEmoji: string, violations: Violation[]): string {
  if (violations.length === 0 || violations.every((v) => !v.message)) {
    return ""
  }
  return `
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">${name}</th>
    </tr>
  </thead>
  <tbody>${violations.map((v) => htmlForValidation(defaultEmoji, v)).join("\n")}</tbody>
</table>
`
}

function htmlForValidation(defaultEmoji: string, violation: Violation): string {
  let message = isInline(violation)
    ? `**${violation.file!}#L${violation.line!}** - ${violation.message}`
    : violation.message

  if (containsMarkdown(message)) {
    message = `\n\n  ${message}\n  `
  }

  const emojiString = `:${defaultEmoji}:`

  return `<tr>
      <td>${violation.icon || emojiString}</td>
      <td>${message}</td>
    </tr>
  `
}

function containsMarkdown(message: string): boolean {
  return /[`*_~\[]+/.test(message)
}

function truncate(msg: string, count: number): string {
  if (!msg || msg.length < count) return msg
  return msg.substring(0, count - 3) + "..."
}

function getSummary(label: string, violations: Violation[]): string {
  return violations
    .map((x) => truncate(x.message, 20))
    .reduce(
      (acc, value, idx) => `${acc} ${value}${idx === violations.length - 1 ? "" : ","}`,
      `${violations.length} ${label}: `
    )
}

function buildSummaryMessage(dangerID: string, results: DangerResults): string {
  const { fails, warnings, messages, markdowns } = results
  return `  ${getSummary("failure", fails)}
  ${getSummary("warning", warnings)}
  ${messages.length > 0 ? `${messages.length} messages` : ""}
  ${markdowns.length > 0 ? `${markdowns.length} markdown notices` : ""}
  ${dangerIDToString(dangerID)}`
}

/** Format: `DangerID: danger-id-{id};` */
export const dangerIDToString = (id: string) => `DangerID: danger-id-${id};`

/** Format file and line info for HTML comments */
export const fileLineToString = (file: string, line: number) =>
  `  File: ${file};\n  Line: ${line};`

/** Generate signature with runtime name and href */
export const dangerSignature = (results: DangerResults) => {
  const meta = results.meta || {
    runtimeName: "dangerJS",
    runtimeHref: "https://danger.systems/js",
  }
  return `Generated by :no_entry_sign: <a href="${meta.runtimeHref}">${meta.runtimeName}</a>`
}

/** Full signature with optional commit ID */
export const dangerSignaturePostfix = (results: DangerResults, commitID?: string) => {
  let signature = dangerSignature(results)
  if (commitID !== undefined) {
    signature = `${signature} against ${commitID}`
  }
  return signature
}

/** Comment to show when issues are found */
export const messageForResultWithIssues = `Found some issues. Don't worry, everything is fixable.`

/**
 * Creates a GitHub issue comment from Danger Results.
 */
export function template(dangerID: string, results: DangerResults, commitID?: string): string {
  return `
<!--
${buildSummaryMessage(dangerID, results)}
-->
${table("Fails", "no_entry_sign", results.fails)}
${table("Warnings", "warning", results.warnings)}
${table("Messages", "book", results.messages)}
${results.markdowns.map((v) => v.message).join("\n\n")}
<p align="right">
  ${dangerSignaturePostfix(results, commitID)}
</p>
`
}

/**
 * Creates an inline comment from Danger Results for a specific file/line.
 */
export function inlineTemplate(
  dangerID: string,
  results: DangerResults,
  file: string,
  line: number
): string {
  const printViolation = (defaultEmoji: string) => (violation: Violation) => {
    const emojiString = `:${defaultEmoji}:`
    return `- ${violation.icon || emojiString} ${violation.message}`
  }

  return `
<!--
${buildSummaryMessage(dangerID, results)}
${fileLineToString(file, line)}
-->
${results.fails.map(printViolation("no_entry_sign")).join("\n")}
${results.warnings.map(printViolation("warning")).join("\n")}
${results.messages.map(printViolation("book")).join("\n")}
${results.markdowns.map((v) => v.message).join("\n\n")}
  `
}
